#!/usr/bin/env node

/**
 * Script to generate frontend ABI and address files from backend deployments
 * Automatically reads deployment records and generates TypeScript files
 * Skips deployments that don't exist
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const backendDir = join(__dirname, '../../backend');
const frontendDir = join(__dirname, '..');
const abiDir = join(frontendDir, 'abi');

// Chain configurations
const CHAINS = {
  '31337': { chainId: 31337, chainName: 'localhost', network: 'hardhat' },
  '11155111': { chainId: 11155111, chainName: 'sepolia', network: 'sepolia' },
};

// Contract name
const CONTRACT_NAME = 'Ledger';

/**
 * Read deployment record from hardhat-deploy
 */
function readDeployment(network) {
  const deploymentPath = join(backendDir, 'deployments', network, `${CONTRACT_NAME}.json`);
  
  if (!existsSync(deploymentPath)) {
    return null;
  }

  try {
    const content = readFileSync(deploymentPath, 'utf-8');
    const deployment = JSON.parse(content);
    return deployment;
  } catch (error) {
    console.warn(`Warning: Failed to read deployment for ${network}:`, error.message);
    return null;
  }
}

/**
 * Read ABI from artifacts
 */
function readABI() {
  const artifactPath = join(backendDir, 'artifacts', 'contracts', `${CONTRACT_NAME}.sol`, `${CONTRACT_NAME}.json`);
  
  if (!existsSync(artifactPath)) {
    throw new Error(`ABI file not found: ${artifactPath}\nPlease compile contracts first: cd backend && npm run compile`);
  }

  try {
    const content = readFileSync(artifactPath, 'utf-8');
    const artifact = JSON.parse(content);
    return artifact.abi;
  } catch (error) {
    throw new Error(`Failed to read ABI: ${error.message}`);
  }
}

/**
 * Generate ABI TypeScript file
 */
function generateABIFile(abi) {
  const abiContent = `// Auto-generated by genabi.mjs
// Do not edit manually - run 'npm run genabi' to regenerate

export const LedgerABI = ${JSON.stringify(abi, null, 2)} as const;
`;

  if (!existsSync(abiDir)) {
    mkdirSync(abiDir, { recursive: true });
  }

  const abiFilePath = join(abiDir, 'LedgerABI.ts');
  writeFileSync(abiFilePath, abiContent, 'utf-8');
  console.log(`✓ Generated: ${abiFilePath}`);
}

/**
 * Generate addresses TypeScript file
 */
function generateAddressesFile(addresses) {
  const addressesContent = `// Auto-generated by genabi.mjs
// Do not edit manually - run 'npm run genabi' to regenerate

export const LedgerAddresses: Record<string, { address: \`0x\${string}\`; chainId: number; chainName: string }> = ${JSON.stringify(addresses, null, 2)};
`;

  const addressesFilePath = join(abiDir, 'LedgerAddresses.ts');
  writeFileSync(addressesFilePath, addressesContent, 'utf-8');
  console.log(`✓ Generated: ${addressesFilePath}`);
}

/**
 * Main function
 */
function main() {
  console.log('Generating frontend ABI and address files...\n');

  // Read ABI
  let abi;
  try {
    abi = readABI();
    console.log('✓ ABI loaded from artifacts');
  } catch (error) {
    console.error('✗ Error:', error.message);
    process.exit(1);
  }

  // Read deployments
  const addresses = {};
  
  for (const [chainIdStr, chainConfig] of Object.entries(CHAINS)) {
    const deployment = readDeployment(chainConfig.network);
    
    if (deployment && deployment.address) {
      addresses[chainIdStr] = {
        address: deployment.address,
        chainId: chainConfig.chainId,
        chainName: chainConfig.chainName,
      };
      console.log(`✓ Found deployment for ${chainConfig.chainName} (${chainIdStr}): ${deployment.address}`);
    } else {
      console.log(`⊘ No deployment found for ${chainConfig.chainName} (${chainIdStr}) - skipping`);
    }
  }

  // Generate files
  generateABIFile(abi);
  generateAddressesFile(addresses);

  console.log('\n✓ Generation complete!');
  
  if (Object.keys(addresses).length === 0) {
    console.log('\n⚠ Warning: No deployments found. Deploy contracts first:');
    console.log('  - Local: cd backend && npm run deploy:local');
    console.log('  - Sepolia: cd backend && npm run deploy:sepolia');
  }
}

main();

