// Auto-generated by genabi.mjs
// Do not edit manually - run 'npm run genabi' to regenerate

export const LedgerAddresses: Record<string, { address: `0x${string}`; chainId: number; chainName: string }> = {
  "11155111": {
    "address": "0xf880a4f94EA530337cfDeB9334618441157CF47c",
    "chainId": 11155111,
    "chainName": "sepolia"
  }
};
